# ─────────────────────────────────────────────────────────
# Incubator configuration
# ─────────────────────────────────────────────────────────

log_file: /home/brennan/incubator/incubator.log

gpio:
  o2_pin: 20
  co2_pin: 21
  heaters: [13, 19]

serial:
  baud: 9600
  o2_port: "/dev/serial0"
  o2_cmd: "%"
  o2_scale: 0.001
  co2_port: "/dev/ttyUSB0"
  co2_cmd: "Z"
  co2_scale: 10/10000.0

i2c:
  disp_o2: 0x70
  disp_co2: 0x71
  disp_temp: 0x72

setpoints:
  temperature: 37.0
  o2: 3.0
  co2: 5.0

thresholds:
  # heater uses a single threshold (0…1) for switching to the PID regime
  temperature: 0.98

  # gas controllers get three thresholds: continuous, pulse, off
  o2:
    continuous: 1.25   # if O₂ > setpt*1.25 → continuous N₂ purge
    pulse:      1.10   # if O₂ > setpt*1.10 → pulsed purge
    off:        0.90   # if O₂ < setpt*0.90 → absolutely off

  co2:
    continuous: 0.75   # if CO₂ < setpt*0.75 → continuous CO₂ in
    pulse:      0.90   # if CO₂ < setpt*0.90 → pulsed injection
    off:        1.10   # if CO₂ > setpt*1.10 → absolutely off

pid:
  heater:
    Kp:  1.0
    Ki:  0.1
    Kd:  0.01

max_values:
  o2:          25.0    # chart limits
  co2:         10.0
  temperature: 50.0

read_interval: 0.5      # seconds between main loop iterations
